### ISSUE TITLE
Odd behaviour

### ISSUE THREAD

**Issue by cristianc** [makefool163/HuaweiHonorBootloaderHack#1]
I've tried this thing a bit. When I run `munlock.py` python script, I notice this line: `working_Count  299344`
Going on, a long series of `#` in the terminal, one by one (this goes on for hours). After some hours, I've noticed android was turned on (not in android bootloader anymore) but the script still runs and prints `#`s  again and again, as before.
Is that normal? I wonder: does this script actually make anything?

Waiting for a reply, thanks.

**Comment by makefool163** [comment]
I'd tryed it in my Honor cellphone, it can't work.
Someone said that munlock.py maybe only work on Honor cellphone selled in Europe.

**Comment by cristianc** [comment]
> I'd tryed it in my Honor cellphone, it can't work. Someone said that munlock.py maybe only work on Honor cellphone selled in Europe.

Someone? Who are you talking about?
